/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez.vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ligaajedrez.modelo.Administrador;
import ligaajedrez.modelo.EntrenadorModel;
import ligaajedrez.modelo.GerenteModel;
import ligaajedrez.modelo.Usuario;

/**
 *
 * @author asins
 */
public class AsignClub extends javax.swing.JFrame {

    private Usuario usuario;
    private JFrame previousView;
    private JFrame menuView;
    private EntrenadorModel entrenador;
    private GerenteModel gerente;

    /**
     * Creates new form ConsultarJugadores
     */
    public AsignClub(Usuario usuario, JFrame previousView, JFrame menuView, EntrenadorModel entrenador) {
        initComponents();
        this.usuario = usuario;
        this.previousView = previousView;
        this.menuView = menuView;
        this.entrenador = entrenador;
        mostrarClubs();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                usuario.saveData();
                e.getWindow().dispose();
            }
        });
    }
    
    public AsignClub(Usuario usuario, JFrame previousView, JFrame menuView, GerenteModel gerente) {
        initComponents();
        this.usuario = usuario;
        this.previousView = previousView;
        this.menuView = menuView;
        this.gerente = gerente;
        mostrarClubs();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                usuario.saveData();
                e.getWindow().dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clubsList = new javax.swing.JList<>();
        atrasButton = new javax.swing.JButton();
        addClub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clubsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(clubsList);

        atrasButton.setText("Atrás");
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });

        addClub.setText("Añadir");
        addClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addClub, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClub, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarClubs() {
        ArrayList clubs = usuario.consultarClubs();
        DefaultListModel modeloLista = new DefaultListModel();
        clubsList.setModel(modeloLista);

        if (!clubs.isEmpty()) {
            for (Object j : clubs) {
                modeloLista.addElement(j);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay clubs para mostrar en estos momentos.");
        }
    }

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        // TODO add your handling code here:
        previousView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasButtonActionPerformed

    private void addClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClubActionPerformed
        if (entrenador != null) {
            ((Administrador) usuario).asignarClubEntrenador(entrenador, clubsList.getSelectedValue());
            menuView.setVisible(true);
            this.setVisible(false);
        } else if (gerente != null) {
            ((Administrador) usuario).asignarClubGerente(gerente, clubsList.getSelectedValue());
            menuView.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_addClubActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClub;
    private javax.swing.JButton atrasButton;
    private javax.swing.JList<Object> clubsList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
