/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez.vista;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ligaajedrez.modelo.Administrador;
import ligaajedrez.modelo.Usuario;

/**
 *
 * @author asins
 */
public class RegistrarPartida extends javax.swing.JFrame {
    private JFrame vAnterior;
    private Usuario usuario;
    /**
     * Creates new form RegistrarPartida
     */
    public RegistrarPartida(Usuario _usuario, JFrame Vanterior) {
        initComponents();
        usuario = _usuario;
        this.vAnterior = Vanterior;
        
        /*ArrayList jugadores = this.administrador.consultarJugadores();
        jugador1Combo.removeAllItems();
        for (Object jugador : jugadores) {
            jugador1Combo.addItem((String) jugador);
        }
        
        jugador2Combo.removeAllItems();
        for (Object jugador : jugadores) {
            jugador1Combo.addItem((String) jugador);
        }
        
        ArrayList sedes = administrador.consultarSedes();
        sedeCombo.removeAllItems();
        for (Object sede : sedes) {
            sedeCombo.addItem(sede.toString());
        }
        
        ArrayList torneos = administrador.consultarTorneos();
        torneoCombo.removeAllItems();
        for (Object torneo : torneos) {
            torneoCombo.addItem(torneo);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugador1Label = new javax.swing.JLabel();
        jugador2Label = new javax.swing.JLabel();
        sedeLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        horaLabel = new javax.swing.JLabel();
        torneoLabel = new javax.swing.JLabel();
        jugador1Combo = new javax.swing.JComboBox<>();
        jugador2Combo = new javax.swing.JComboBox<>();
        sedeCombo = new javax.swing.JComboBox<>();
        torneoCombo = new javax.swing.JComboBox<>();
        FechaField = new javax.swing.JTextField();
        HoraField = new javax.swing.JTextField();
        confirmarButton = new javax.swing.JButton();
        atrasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jugador1Label.setText("Jugador 1");

        jugador2Label.setText("Jugador 2");

        sedeLabel.setText("Sede");

        fechaLabel.setText("Fecha");

        horaLabel.setText("Hora");

        torneoLabel.setText("Torneo");

        jugador1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugador X", "Jugador Y" }));

        jugador2Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugador Y", "Jugador Z" }));

        sedeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sede 1", "Sede 2" }));

        torneoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Torneo 1", "Torneo 2" }));

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        atrasButton.setText("Atrás");
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(horaLabel)
                                .addGap(113, 113, 113)
                                .addComponent(HoraField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jugador1Label)
                                    .addComponent(jugador2Label)
                                    .addComponent(sedeLabel)
                                    .addComponent(torneoLabel)
                                    .addComponent(fechaLabel))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(torneoCombo, 0, 150, Short.MAX_VALUE)
                                    .addComponent(sedeCombo, 0, 150, Short.MAX_VALUE)
                                    .addComponent(jugador2Combo, 0, 150, Short.MAX_VALUE)
                                    .addComponent(jugador1Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FechaField))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador1Label)
                    .addComponent(jugador1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador2Label)
                    .addComponent(jugador2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sedeLabel)
                    .addComponent(sedeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(FechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaLabel)
                    .addComponent(HoraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(torneoLabel)
                    .addComponent(torneoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        // TODO add your handling code here:
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasButtonActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        // TODO add your handling code here:
        //administrador.crearPartida(jugador1Combo.getSelectedItem(),jugador2Combo.getSelectedItem(), sedeCombo.getSelectedItem(), FechaField.getText(),HoraField.getText(),torneoCombo.getSelectedItem());
        JOptionPane.showMessageDialog(this, "Partida registrada");
        vAnterior.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_confirmarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FechaField;
    private javax.swing.JTextField HoraField;
    private javax.swing.JButton atrasButton;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JComboBox<String> jugador1Combo;
    private javax.swing.JLabel jugador1Label;
    private javax.swing.JComboBox<String> jugador2Combo;
    private javax.swing.JLabel jugador2Label;
    private javax.swing.JComboBox<String> sedeCombo;
    private javax.swing.JLabel sedeLabel;
    private javax.swing.JComboBox<String> torneoCombo;
    private javax.swing.JLabel torneoLabel;
    // End of variables declaration//GEN-END:variables
}
